spring:
  datasource:
    url: jdbc:mysql://localhost:3306/water?useSSL=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 159645
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mybatis-mapper/*.xml